### ISSUE TITLE
没有生成TOC 如何调试呢？

### ISSUE THREAD

**Issue by 0xAlbertChen** [ZHD99/hexo-theme-dearmsdan#1]
![image](https://user-images.githubusercontent.com/2715268/80592870-be20e680-8a52-11ea-88a7-d299fee70fb2.png)

**Comment by ZHD99** [comment]
Is the corresponding plug-in installed

**Comment by ZHD99** [comment]
npm install hexo-wordcount --save  
npm install hexo-toc --save  
npm install hexo-generator-search --save  
npm install hexo-generator-searchdb --save

**Comment by ZHD99** [comment]
问题已解决，最新版本，弃用全部插件，关于目录方面 ，我使用了hexo 自带的辅助函数，无需安装插件，感谢您使用过本主题~
