### ISSUE TITLE
评论系统如何加入呢

### ISSUE THREAD

**Issue by victorydxy** [ZHD99/hexo-theme-dearmsdan#2]
评论系统如何加入呢

**Comment by ZHD99** [comment]
昨天晚上我写好了个valine 评论， 如果要文章评论 需要关闭pjax，然后就能显示了，当然需要您先配置下 valine  APP ID 和 APP Key信息 等等....

**Comment by ZHD99** [comment]
我现在在写网页的显示样式，我感觉移动端悬浮有点儿 不好看

**Comment by ZHD99** [comment]
等我更改网页部分样式和脚本，就写个主题文档，便于大家了解主题，感谢您的使用~
