### ISSUE TITLE
主题预览链接失效了

### ISSUE THREAD

**Issue by Yue-plus** [ZHD99/hexo-theme-dearmsdan#4]
```json
{"code":"40310014","msg":"invalid Referer header"}
```

**Comment by ZHD99** [comment]
> ```json
> { “代码”：“ 40310014 ”，“ msg ”：“无效的引荐标头”“ }
> ```

刷新一下就好了，因为网站设置了防盗链

**Comment by ZHD99** [comment]
> ```json
> {"code":"40310014","msg":"invalid Referer header"}
> ```

网站设置了防盗链，刷新一下就好了

**Comment by Yue-plus** [comment]
又试了一下，Chrome 和 Firefox 能打开，唯独新版 edge 死都刷不出 /笑哭
![QQ截图20200522152008](https://user-images.githubusercontent.com/33195150/82642147-0ee5c280-9c40-11ea-9c80-3396277f5fd1.png)

**Comment by ZHD99** [comment]
是本地测试吗，用谷歌和火狐可以，部署后edge就能访问

________________________________
发件人: Yue_plus <notifications@github.com>
发送时间: Friday, May 22, 2020 3:23:13 PM
收件人: ZHD99/hexo-theme-dearmsdan <hexo-theme-dearmsdan@noreply.github.com>
抄送: 德阿姆斯丹 <dearmsdan@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [ZHD99/hexo-theme-dearmsdan] 主题预览链接失效了 (#4)


又试了一下，Chrome 和 Firefox 能打开，唯独新版 edge 死都刷不出 /笑哭
[QQ截图20200522152008]<https://user-images.githubusercontent.com/33195150/82642147-0ee5c280-9c40-11ea-9c80-3396277f5fd1.png>

―

**Comment by Yue-plus** [comment]
现在能访问了，应该是我浏览器插件的问题233333

**Comment by ZHD99** [comment]
> 现在能访问了，应该是我浏览器插件的问题233333

嗯嗯
