### ISSUE TITLE
尝试开启latex替换引擎后无法正常打开页面

### ISSUE THREAD

**Issue by TimeInDreams** [ZHD99/hexo-theme-dearmsdan#6]
https://www.jianshu.com/p/9b9c241146bc      按照此教程进行引擎替换，需要latex功能，做完后页面加载失败

**Comment by ZHD99** [comment]
有截图吗，看看什么情况

**Comment by TimeInDreams** [comment]
> 有截图吗，看看什么情况

![image](https://user-images.githubusercontent.com/56781415/106836396-0a7d0f00-66d4-11eb-985e-36429f659a53.png)
![image](https://user-images.githubusercontent.com/56781415/106836432-22549300-66d4-11eb-8698-e8b21b7f2f88.png)
![image](https://user-images.githubusercontent.com/56781415/106836457-2bddfb00-66d4-11eb-99c2-ef24af20b0fb.png)
以上为打开本地hexo server报错
![image](https://user-images.githubusercontent.com/56781415/106836508-4021f800-66d4-11eb-9263-b47c8fd08a04.png)
以上为hexo clean,hexo g,hexo d部署后的加载失败页面

**Comment by ZHD99** [comment]
我能下午解决这个问题吗，我现在忙

**Comment by TimeInDreams** [comment]
> 我能下午解决这个问题吗，我现在忙
不着急，麻烦您了

**Comment by ZHD99** [comment]
我需要需要花段时间来优化代码以及添加置顶功能[需要添加插件]与无需安装插件的公式功能，你这个问题貌似是引擎失去，重新删除npm包，重新install 试试，敬请等待更新吧.....

**Comment by hearxs** [comment]
> https://www.jianshu.com/p/9b9c241146bc 按照此教程进行引擎替换，需要latex功能，做完后页面加载失败

您好，主题已更新，自带公式功能，无需安装插件
更新请注意备份原配置文件
